/**
 * Copyright 2017 FlashAir Developers
 * 
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 * 
 *   http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

export const AppEvent = {
  DID_FINISH_LOAD: 'did-finish-load',
  // initialize event
  UPDATE_TOKEN: 'UPDATE_TOKEN',
  INVALID_TOKEN: 'INVALID_TOKEN',
  INIT_STATE: 'INIT_STATE',
  // filer event
  ADD_REMOTE_JOB: 'ADD_REMOTE_JOB',
  FETCH_FLASHAIRS: 'FETCH_FLASHAIRS',
  FETCH_FLASHAIRS_SUCCESS: 'FETCH_FLASHAIRS_SUCCESS',
  FETCH_FLASHAIRS_FAILURE: 'FETCH_FLASHAIRS_FAILURE',
  CHANGE_FLASHAIR: 'CHANGE_FLASHAIR',
  GET_REMOTE_JOB: 'GET_REMOTE_JOB',
  GET_REMOTE_JOB_SUCCESS: 'GET_REMOTE_JOB_SUCCESS',
  GET_REMOTE_JOB_FAILURE: 'GET_REMOTE_JOB_FAILURE',
  DELETE_REMOTE_JOB: 'DELETE_REMOTE_JOB',
  DELETE_REMOTE_JOB_SUCCESS: 'DELETE_REMOTE_JOB_SUCCESS',
  DELETE_REMOTE_JOB_FAILURE: 'DELETE_REMOTE_JOB_FAILURE',
  GET_LOCAL_FILE_LIST: 'GET_LOCAL_FILE_LIST',
  GET_LOCAL_FILE_LIST_SUCCESS: 'GET_LOCAL_FILE_LIST_SUCCESS',
  GET_LOCAL_FILE_LIST_FAILURE: 'GET_LOCAL_FILE_LIST_FAILURE',
  REQUEST_REMOTE_FILE_LIST: 'REQUEST_REMOTE_FILE_LIST',
  REQUEST_REMOTE_FILE_LIST_SUCCESS: 'REQUEST_REMOTE_FILE_LIST_SUCCESS',
  REQUEST_REMOTE_FILE_LIST_FAILURE: 'REQUEST_REMOTE_FILE_LIST_FAILURE',
  UPDATE_REMOTE_FILE_LIST: 'UPDATE_REMOTE_FILE_LIST',
  SELECT_REMOTE_FILE: 'SELECT_REMOTE_FILE',
  REQUEST_TRANSFER_REMOTE_TO_IOTHUB: 'REQUEST_TRANSFER_REMOTE_TO_IOTHUB',
  REQUEST_TRANSFER_REMOTE_TO_IOTHUB_SUCCESS: 'REQUEST_TRANSFER_REMOTE_TO_IOTHUB_SUCCESS',
  REQUEST_TRANSFER_REMOTE_TO_IOTHUB_FAILURE: 'REQUEST_TRANSFER_REMOTE_TO_IOTHUB_FAILURE',
  DOWNLOAD_REMOTE_FILE: 'DOWNLOAD_REMOTE_FILE',
  DOWNLOAD_REMOTE_FILE_PROGRESS: 'DOWNLOAD_REMOTE_FILE_PROGRESS',
  DOWNLOAD_REMOTE_FILE_SUCCESS: 'DOWNLOAD_REMOTE_FILE_SUCCESS',
  DOWNLOAD_REMOTE_FILE_FAILURE: 'DOWNLOAD_REMOTE_FILE_FAILURE',
  GET_DOWNLOAD_PROGRESS: 'GET_DOWNLOAD_PROGRESS',
  GET_DOWNLOAD_PROGRESS_SUCCESS: 'GET_DOWNLOAD_PROGRESS_SUCCESS',
  GET_DOWNLOAD_PROGRESS_FAILURE: 'GET_DOWNLOAD_PROGRESS_FAILURE',
  LOGOUT_IOTHUB: 'LOGOUT_IOTHUB',
  LOGOUT_IOTHUB_SUCCESS: 'LOGOUT_IOTHUB_SUCCESS',
  LOGOUT_IOTHUB_FAILURE: 'LOGOUT_IOTHUB_FAILURE',
};